package plus.bookshelf.Dao.DO;

public class BookDO extends BookDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.category_id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.publishing_house_id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Integer publishingHouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.language
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.copyright
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private String copyright;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.is_delete
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.description
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.category_id
     *
     * @return the value of book_info.category_id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.category_id
     *
     * @param categoryId the value for book_info.category_id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.publishing_house_id
     *
     * @return the value of book_info.publishing_house_id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Integer getPublishingHouseId() {
        return publishingHouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.publishing_house_id
     *
     * @param publishingHouseId the value for book_info.publishing_house_id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setPublishingHouseId(Integer publishingHouseId) {
        this.publishingHouseId = publishingHouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.language
     *
     * @return the value of book_info.language
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.language
     *
     * @param language the value for book_info.language
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.copyright
     *
     * @return the value of book_info.copyright
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.copyright
     *
     * @param copyright the value for book_info.copyright
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setCopyright(String copyright) {
        this.copyright = copyright == null ? null : copyright.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.is_delete
     *
     * @return the value of book_info.is_delete
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.is_delete
     *
     * @param isDelete the value for book_info.is_delete
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.description
     *
     * @return the value of book_info.description
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.description
     *
     * @param description the value for book_info.description
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}