package plus.bookshelf.Dao.DO;

public class BookDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Byte id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_info.book_name
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private String bookName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.id
     *
     * @return the value of book_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.id
     *
     * @param id the value for book_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_info.book_name
     *
     * @return the value of book_info.book_name
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_info.book_name
     *
     * @param bookName the value for book_info.book_name
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }
}