package plus.bookshelf.Dao.DO;

public class CategoryDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_info.name
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_info.isShow
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Boolean isshow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_info.order
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Integer order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_info.level
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_info.parentId
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category_info.description
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_info.id
     *
     * @return the value of category_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_info.id
     *
     * @param id the value for category_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_info.name
     *
     * @return the value of category_info.name
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_info.name
     *
     * @param name the value for category_info.name
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_info.isShow
     *
     * @return the value of category_info.isShow
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Boolean getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_info.isShow
     *
     * @param isshow the value for category_info.isShow
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setIsshow(Boolean isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_info.order
     *
     * @return the value of category_info.order
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_info.order
     *
     * @param order the value for category_info.order
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_info.level
     *
     * @return the value of category_info.level
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_info.level
     *
     * @param level the value for category_info.level
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_info.parentId
     *
     * @return the value of category_info.parentId
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_info.parentId
     *
     * @param parentid the value for category_info.parentId
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category_info.description
     *
     * @return the value of category_info.description
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category_info.description
     *
     * @param description the value for category_info.description
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}