package plus.bookshelf.Dao.DO;

import java.util.Date;

public class FailureFeedbackDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column failure_feedback.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column failure_feedback.file_id
     *
     * @mbg.generated
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column failure_feedback.file_object_id
     *
     * @mbg.generated
     */
    private Integer fileObjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column failure_feedback.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column failure_feedback.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column failure_feedback.book_id
     *
     * @return the value of failure_feedback.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column failure_feedback.book_id
     *
     * @param bookId the value for failure_feedback.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column failure_feedback.file_id
     *
     * @return the value of failure_feedback.file_id
     *
     * @mbg.generated
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column failure_feedback.file_id
     *
     * @param fileId the value for failure_feedback.file_id
     *
     * @mbg.generated
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column failure_feedback.file_object_id
     *
     * @return the value of failure_feedback.file_object_id
     *
     * @mbg.generated
     */
    public Integer getFileObjectId() {
        return fileObjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column failure_feedback.file_object_id
     *
     * @param fileObjectId the value for failure_feedback.file_object_id
     *
     * @mbg.generated
     */
    public void setFileObjectId(Integer fileObjectId) {
        this.fileObjectId = fileObjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column failure_feedback.user_id
     *
     * @return the value of failure_feedback.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column failure_feedback.user_id
     *
     * @param userId the value for failure_feedback.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column failure_feedback.create_time
     *
     * @return the value of failure_feedback.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column failure_feedback.create_time
     *
     * @param createTime the value for failure_feedback.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}