package plus.bookshelf.Dao.DO;

import java.util.Date;

public class FileOperationDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_operation_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_operation_log.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_operation_log.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_operation_log.expire_minute
     *
     * @mbg.generated
     */
    private String expireMinute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_operation_log.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_operation_log.file_path
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_operation_log.url_guid
     *
     * @mbg.generated
     */
    private String urlGuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_operation_log.id
     *
     * @return the value of file_operation_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_operation_log.id
     *
     * @param id the value for file_operation_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_operation_log.user_id
     *
     * @return the value of file_operation_log.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_operation_log.user_id
     *
     * @param userId the value for file_operation_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_operation_log.time
     *
     * @return the value of file_operation_log.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_operation_log.time
     *
     * @param time the value for file_operation_log.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_operation_log.expire_minute
     *
     * @return the value of file_operation_log.expire_minute
     *
     * @mbg.generated
     */
    public String getExpireMinute() {
        return expireMinute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_operation_log.expire_minute
     *
     * @param expireMinute the value for file_operation_log.expire_minute
     *
     * @mbg.generated
     */
    public void setExpireMinute(String expireMinute) {
        this.expireMinute = expireMinute == null ? null : expireMinute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_operation_log.method
     *
     * @return the value of file_operation_log.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_operation_log.method
     *
     * @param method the value for file_operation_log.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_operation_log.file_path
     *
     * @return the value of file_operation_log.file_path
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_operation_log.file_path
     *
     * @param filePath the value for file_operation_log.file_path
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_operation_log.url_guid
     *
     * @return the value of file_operation_log.url_guid
     *
     * @mbg.generated
     */
    public String getUrlGuid() {
        return urlGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_operation_log.url_guid
     *
     * @param urlGuid the value for file_operation_log.url_guid
     *
     * @mbg.generated
     */
    public void setUrlGuid(String urlGuid) {
        this.urlGuid = urlGuid == null ? null : urlGuid.trim();
    }
}