package plus.bookshelf.Dao.DO;

import java.util.Date;

public class FileDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.id
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.book_id
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_display_name
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private String fileDisplayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_name
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_format
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private String fileFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.number_of_pages
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private Integer numberOfPages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.watermark
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private Boolean watermark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.advertising
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private Boolean advertising;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.book_origin
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private Byte bookOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.thumbnail
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private String thumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_create_at
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private Date fileCreateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_modified_at
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private Date fileModifiedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_size
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private Integer fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.hash_md5
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private String hashMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.hash_sha1
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private String hashSha1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.hash_sha256
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    private String hashSha256;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.id
     *
     * @return the value of file_info.id
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.id
     *
     * @param id the value for file_info.id
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.book_id
     *
     * @return the value of file_info.book_id
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.book_id
     *
     * @param bookId the value for file_info.book_id
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_display_name
     *
     * @return the value of file_info.file_display_name
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public String getFileDisplayName() {
        return fileDisplayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_display_name
     *
     * @param fileDisplayName the value for file_info.file_display_name
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setFileDisplayName(String fileDisplayName) {
        this.fileDisplayName = fileDisplayName == null ? null : fileDisplayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_name
     *
     * @return the value of file_info.file_name
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_name
     *
     * @param fileName the value for file_info.file_name
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_format
     *
     * @return the value of file_info.file_format
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public String getFileFormat() {
        return fileFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_format
     *
     * @param fileFormat the value for file_info.file_format
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setFileFormat(String fileFormat) {
        this.fileFormat = fileFormat == null ? null : fileFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.number_of_pages
     *
     * @return the value of file_info.number_of_pages
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public Integer getNumberOfPages() {
        return numberOfPages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.number_of_pages
     *
     * @param numberOfPages the value for file_info.number_of_pages
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setNumberOfPages(Integer numberOfPages) {
        this.numberOfPages = numberOfPages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.watermark
     *
     * @return the value of file_info.watermark
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public Boolean getWatermark() {
        return watermark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.watermark
     *
     * @param watermark the value for file_info.watermark
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setWatermark(Boolean watermark) {
        this.watermark = watermark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.advertising
     *
     * @return the value of file_info.advertising
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public Boolean getAdvertising() {
        return advertising;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.advertising
     *
     * @param advertising the value for file_info.advertising
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setAdvertising(Boolean advertising) {
        this.advertising = advertising;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.book_origin
     *
     * @return the value of file_info.book_origin
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public Byte getBookOrigin() {
        return bookOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.book_origin
     *
     * @param bookOrigin the value for file_info.book_origin
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setBookOrigin(Byte bookOrigin) {
        this.bookOrigin = bookOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.thumbnail
     *
     * @return the value of file_info.thumbnail
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.thumbnail
     *
     * @param thumbnail the value for file_info.thumbnail
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_create_at
     *
     * @return the value of file_info.file_create_at
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public Date getFileCreateAt() {
        return fileCreateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_create_at
     *
     * @param fileCreateAt the value for file_info.file_create_at
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setFileCreateAt(Date fileCreateAt) {
        this.fileCreateAt = fileCreateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_modified_at
     *
     * @return the value of file_info.file_modified_at
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public Date getFileModifiedAt() {
        return fileModifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_modified_at
     *
     * @param fileModifiedAt the value for file_info.file_modified_at
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setFileModifiedAt(Date fileModifiedAt) {
        this.fileModifiedAt = fileModifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_size
     *
     * @return the value of file_info.file_size
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public Integer getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_size
     *
     * @param fileSize the value for file_info.file_size
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.hash_md5
     *
     * @return the value of file_info.hash_md5
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public String getHashMd5() {
        return hashMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.hash_md5
     *
     * @param hashMd5 the value for file_info.hash_md5
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setHashMd5(String hashMd5) {
        this.hashMd5 = hashMd5 == null ? null : hashMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.hash_sha1
     *
     * @return the value of file_info.hash_sha1
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public String getHashSha1() {
        return hashSha1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.hash_sha1
     *
     * @param hashSha1 the value for file_info.hash_sha1
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setHashSha1(String hashSha1) {
        this.hashSha1 = hashSha1 == null ? null : hashSha1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.hash_sha256
     *
     * @return the value of file_info.hash_sha256
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public String getHashSha256() {
        return hashSha256;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.hash_sha256
     *
     * @param hashSha256 the value for file_info.hash_sha256
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    public void setHashSha256(String hashSha256) {
        this.hashSha256 = hashSha256 == null ? null : hashSha256.trim();
    }
}