package plus.bookshelf.Dao.DO;

public class FileDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.book_id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Integer bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.id
     *
     * @return the value of file_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.id
     *
     * @param id the value for file_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.book_id
     *
     * @return the value of file_info.book_id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.book_id
     *
     * @param bookId the value for file_info.book_id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
}