package plus.bookshelf.Dao.DO;

public class PublishingHouseDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_house_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_publishing_house_info.name
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_house_info.id
     *
     * @return the value of book_publishing_house_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_house_info.id
     *
     * @param id the value for book_publishing_house_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_publishing_house_info.name
     *
     * @return the value of book_publishing_house_info.name
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_publishing_house_info.name
     *
     * @param name the value for book_publishing_house_info.name
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}