package plus.bookshelf.Dao.DO;

import java.util.Date;

public class ScheduleTaskDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.schedule_time
     *
     * @mbg.generated
     */
    private Date scheduleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.data
     *
     * @mbg.generated
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.task_guid
     *
     * @mbg.generated
     */
    private String taskGuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.associated_user_id
     *
     * @mbg.generated
     */
    private Integer associatedUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_task.fail_time
     *
     * @mbg.generated
     */
    private Byte failTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.id
     *
     * @return the value of schedule_task.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.id
     *
     * @param id the value for schedule_task.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.create_time
     *
     * @return the value of schedule_task.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.create_time
     *
     * @param createTime the value for schedule_task.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.schedule_time
     *
     * @return the value of schedule_task.schedule_time
     *
     * @mbg.generated
     */
    public Date getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.schedule_time
     *
     * @param scheduleTime the value for schedule_task.schedule_time
     *
     * @mbg.generated
     */
    public void setScheduleTime(Date scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.action
     *
     * @return the value of schedule_task.action
     *
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.action
     *
     * @param action the value for schedule_task.action
     *
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.data
     *
     * @return the value of schedule_task.data
     *
     * @mbg.generated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.data
     *
     * @param data the value for schedule_task.data
     *
     * @mbg.generated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.task_guid
     *
     * @return the value of schedule_task.task_guid
     *
     * @mbg.generated
     */
    public String getTaskGuid() {
        return taskGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.task_guid
     *
     * @param taskGuid the value for schedule_task.task_guid
     *
     * @mbg.generated
     */
    public void setTaskGuid(String taskGuid) {
        this.taskGuid = taskGuid == null ? null : taskGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.associated_user_id
     *
     * @return the value of schedule_task.associated_user_id
     *
     * @mbg.generated
     */
    public Integer getAssociatedUserId() {
        return associatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.associated_user_id
     *
     * @param associatedUserId the value for schedule_task.associated_user_id
     *
     * @mbg.generated
     */
    public void setAssociatedUserId(Integer associatedUserId) {
        this.associatedUserId = associatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_task.fail_time
     *
     * @return the value of schedule_task.fail_time
     *
     * @mbg.generated
     */
    public Byte getFailTime() {
        return failTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_task.fail_time
     *
     * @param failTime the value for schedule_task.fail_time
     *
     * @mbg.generated
     */
    public void setFailTime(Byte failTime) {
        this.failTime = failTime;
    }
}