package plus.bookshelf.Dao.DO;

public class ThirdPartyUserAuthDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_auth_relation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_auth_relation.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_auth_relation.third_party_user_id
     *
     * @mbg.generated
     */
    private String thirdPartyUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_auth_relation.id
     *
     * @return the value of third_party_user_auth_relation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_auth_relation.id
     *
     * @param id the value for third_party_user_auth_relation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_auth_relation.user_id
     *
     * @return the value of third_party_user_auth_relation.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_auth_relation.user_id
     *
     * @param userId the value for third_party_user_auth_relation.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_auth_relation.third_party_user_id
     *
     * @return the value of third_party_user_auth_relation.third_party_user_id
     *
     * @mbg.generated
     */
    public String getThirdPartyUserId() {
        return thirdPartyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_auth_relation.third_party_user_id
     *
     * @param thirdPartyUserId the value for third_party_user_auth_relation.third_party_user_id
     *
     * @mbg.generated
     */
    public void setThirdPartyUserId(String thirdPartyUserId) {
        this.thirdPartyUserId = thirdPartyUserId == null ? null : thirdPartyUserId.trim();
    }
}