package plus.bookshelf.Dao.DO;

public class ThirdPartyUserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.access_token
     *
     * @mbg.generated
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.expire_in
     *
     * @mbg.generated
     */
    private Integer expireIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.refresh_token
     *
     * @mbg.generated
     */
    private String refreshToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.access_code
     *
     * @mbg.generated
     */
    private String accessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.union_id
     *
     * @mbg.generated
     */
    private String unionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.scope
     *
     * @mbg.generated
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.token_type
     *
     * @mbg.generated
     */
    private String tokenType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.id_token
     *
     * @mbg.generated
     */
    private String idToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.mac_algorithm
     *
     * @mbg.generated
     */
    private String macAlgorithm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.mac_key
     *
     * @mbg.generated
     */
    private String macKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.oauth_token
     *
     * @mbg.generated
     */
    private String oauthToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_info.oauth_token_secret
     *
     * @mbg.generated
     */
    private String oauthTokenSecret;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.id
     *
     * @return the value of third_party_user_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.id
     *
     * @param id the value for third_party_user_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.uuid
     *
     * @return the value of third_party_user_info.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.uuid
     *
     * @param uuid the value for third_party_user_info.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.source
     *
     * @return the value of third_party_user_info.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.source
     *
     * @param source the value for third_party_user_info.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.access_token
     *
     * @return the value of third_party_user_info.access_token
     *
     * @mbg.generated
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.access_token
     *
     * @param accessToken the value for third_party_user_info.access_token
     *
     * @mbg.generated
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.expire_in
     *
     * @return the value of third_party_user_info.expire_in
     *
     * @mbg.generated
     */
    public Integer getExpireIn() {
        return expireIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.expire_in
     *
     * @param expireIn the value for third_party_user_info.expire_in
     *
     * @mbg.generated
     */
    public void setExpireIn(Integer expireIn) {
        this.expireIn = expireIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.refresh_token
     *
     * @return the value of third_party_user_info.refresh_token
     *
     * @mbg.generated
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.refresh_token
     *
     * @param refreshToken the value for third_party_user_info.refresh_token
     *
     * @mbg.generated
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.open_id
     *
     * @return the value of third_party_user_info.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.open_id
     *
     * @param openId the value for third_party_user_info.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.uid
     *
     * @return the value of third_party_user_info.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.uid
     *
     * @param uid the value for third_party_user_info.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.access_code
     *
     * @return the value of third_party_user_info.access_code
     *
     * @mbg.generated
     */
    public String getAccessCode() {
        return accessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.access_code
     *
     * @param accessCode the value for third_party_user_info.access_code
     *
     * @mbg.generated
     */
    public void setAccessCode(String accessCode) {
        this.accessCode = accessCode == null ? null : accessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.union_id
     *
     * @return the value of third_party_user_info.union_id
     *
     * @mbg.generated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.union_id
     *
     * @param unionId the value for third_party_user_info.union_id
     *
     * @mbg.generated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.scope
     *
     * @return the value of third_party_user_info.scope
     *
     * @mbg.generated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.scope
     *
     * @param scope the value for third_party_user_info.scope
     *
     * @mbg.generated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.token_type
     *
     * @return the value of third_party_user_info.token_type
     *
     * @mbg.generated
     */
    public String getTokenType() {
        return tokenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.token_type
     *
     * @param tokenType the value for third_party_user_info.token_type
     *
     * @mbg.generated
     */
    public void setTokenType(String tokenType) {
        this.tokenType = tokenType == null ? null : tokenType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.id_token
     *
     * @return the value of third_party_user_info.id_token
     *
     * @mbg.generated
     */
    public String getIdToken() {
        return idToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.id_token
     *
     * @param idToken the value for third_party_user_info.id_token
     *
     * @mbg.generated
     */
    public void setIdToken(String idToken) {
        this.idToken = idToken == null ? null : idToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.mac_algorithm
     *
     * @return the value of third_party_user_info.mac_algorithm
     *
     * @mbg.generated
     */
    public String getMacAlgorithm() {
        return macAlgorithm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.mac_algorithm
     *
     * @param macAlgorithm the value for third_party_user_info.mac_algorithm
     *
     * @mbg.generated
     */
    public void setMacAlgorithm(String macAlgorithm) {
        this.macAlgorithm = macAlgorithm == null ? null : macAlgorithm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.mac_key
     *
     * @return the value of third_party_user_info.mac_key
     *
     * @mbg.generated
     */
    public String getMacKey() {
        return macKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.mac_key
     *
     * @param macKey the value for third_party_user_info.mac_key
     *
     * @mbg.generated
     */
    public void setMacKey(String macKey) {
        this.macKey = macKey == null ? null : macKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.code
     *
     * @return the value of third_party_user_info.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.code
     *
     * @param code the value for third_party_user_info.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.oauth_token
     *
     * @return the value of third_party_user_info.oauth_token
     *
     * @mbg.generated
     */
    public String getOauthToken() {
        return oauthToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.oauth_token
     *
     * @param oauthToken the value for third_party_user_info.oauth_token
     *
     * @mbg.generated
     */
    public void setOauthToken(String oauthToken) {
        this.oauthToken = oauthToken == null ? null : oauthToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_info.oauth_token_secret
     *
     * @return the value of third_party_user_info.oauth_token_secret
     *
     * @mbg.generated
     */
    public String getOauthTokenSecret() {
        return oauthTokenSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_info.oauth_token_secret
     *
     * @param oauthTokenSecret the value for third_party_user_info.oauth_token_secret
     *
     * @mbg.generated
     */
    public void setOauthTokenSecret(String oauthTokenSecret) {
        this.oauthTokenSecret = oauthTokenSecret == null ? null : oauthTokenSecret.trim();
    }
}