package plus.bookshelf.Dao.DO;

public class ThirdPartyUserAuthDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_auth_relation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_auth_relation.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column third_party_user_auth_relation.third_party_user_id
     *
     * @mbg.generated
     */
    private Integer thirdPartyUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_auth_relation.id
     *
     * @return the value of third_party_user_auth_relation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_auth_relation.id
     *
     * @param id the value for third_party_user_auth_relation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_auth_relation.user_id
     *
     * @return the value of third_party_user_auth_relation.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_auth_relation.user_id
     *
     * @param userId the value for third_party_user_auth_relation.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column third_party_user_auth_relation.third_party_user_id
     *
     * @return the value of third_party_user_auth_relation.third_party_user_id
     *
     * @mbg.generated
     */
    public Integer getThirdPartyUserId() {
        return thirdPartyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column third_party_user_auth_relation.third_party_user_id
     *
     * @param thirdPartyUserId the value for third_party_user_auth_relation.third_party_user_id
     *
     * @mbg.generated
     */
    public void setThirdPartyUserId(Integer thirdPartyUserId) {
        this.thirdPartyUserId = thirdPartyUserId;
    }
}