package plus.bookshelf.Dao.DO;

public class ThumbnailDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_thumbnail_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_thumbnail_info.path
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_thumbnail_info.id
     *
     * @return the value of book_thumbnail_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_thumbnail_info.id
     *
     * @param id the value for book_thumbnail_info.id
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_thumbnail_info.path
     *
     * @return the value of book_thumbnail_info.path
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_thumbnail_info.path
     *
     * @param path the value for book_thumbnail_info.path
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}