package plus.bookshelf.Dao.DO;

import java.util.Date;

public class UserFavoritesDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_book_favorites_relation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_book_favorites_relation.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_book_favorites_relation.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_book_favorites_relation.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_book_favorites_relation.id
     *
     * @return the value of user_book_favorites_relation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_book_favorites_relation.id
     *
     * @param id the value for user_book_favorites_relation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_book_favorites_relation.user_id
     *
     * @return the value of user_book_favorites_relation.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_book_favorites_relation.user_id
     *
     * @param userId the value for user_book_favorites_relation.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_book_favorites_relation.book_id
     *
     * @return the value of user_book_favorites_relation.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_book_favorites_relation.book_id
     *
     * @param bookId the value for user_book_favorites_relation.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_book_favorites_relation.create_time
     *
     * @return the value of user_book_favorites_relation.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_book_favorites_relation.create_time
     *
     * @param createTime the value for user_book_favorites_relation.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}