package plus.bookshelf.Dao.DO;

import java.util.Date;

public class VisitorFingerprintLogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_fingerprint_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_fingerprint_log.visitor_id
     *
     * @mbg.generated
     */
    private String visitorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_fingerprint_log.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_fingerprint_log.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_fingerprint_log.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_fingerprint_log.id
     *
     * @return the value of visitor_fingerprint_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_fingerprint_log.id
     *
     * @param id the value for visitor_fingerprint_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_fingerprint_log.visitor_id
     *
     * @return the value of visitor_fingerprint_log.visitor_id
     *
     * @mbg.generated
     */
    public String getVisitorId() {
        return visitorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_fingerprint_log.visitor_id
     *
     * @param visitorId the value for visitor_fingerprint_log.visitor_id
     *
     * @mbg.generated
     */
    public void setVisitorId(String visitorId) {
        this.visitorId = visitorId == null ? null : visitorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_fingerprint_log.user_id
     *
     * @return the value of visitor_fingerprint_log.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_fingerprint_log.user_id
     *
     * @param userId the value for visitor_fingerprint_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_fingerprint_log.create_at
     *
     * @return the value of visitor_fingerprint_log.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_fingerprint_log.create_at
     *
     * @param createAt the value for visitor_fingerprint_log.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_fingerprint_log.action
     *
     * @return the value of visitor_fingerprint_log.action
     *
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_fingerprint_log.action
     *
     * @param action the value for visitor_fingerprint_log.action
     *
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }
}