package plus.bookshelf.Dao.Mapper;

import plus.bookshelf.Dao.DO.AuthorDO;

public interface AuthorDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int insert(AuthorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int insertSelective(AuthorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    AuthorDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int updateByPrimaryKeySelective(AuthorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_author_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int updateByPrimaryKey(AuthorDO record);
}