package plus.bookshelf.Dao.Mapper;

import java.util.List;

import org.springframework.stereotype.Repository;
import plus.bookshelf.Dao.DO.BookDO;
import plus.bookshelf.Dao.DO.BookDOExample;

@Repository // 添加这个注解，Autowired的时候idea就不会报错了
public interface BookDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated
     */
    int insert(BookDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated
     */
    int insertSelective(BookDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated
     */
    List<BookDO> selectByExampleWithBLOBs(BookDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated
     */
    List<BookDO> selectByExample(BookDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated
     */
    BookDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BookDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(BookDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BookDO row);

    /**
     * 通过用户id获取用户收藏书籍列表
     * @param userId
     * @return
     */
    BookDO[] selectFavoritesListByUserId(Integer userId);
}