package plus.bookshelf.Dao.Mapper;

import plus.bookshelf.Dao.DO.BookDO;

public interface BookDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    int insert(BookDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    int insertSelective(BookDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    BookDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    int updateByPrimaryKeySelective(BookDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    int updateByPrimaryKeyWithBLOBs(BookDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_info
     *
     * @mbg.generated Sat Mar 12 21:38:13 SGT 2022
     */
    int updateByPrimaryKey(BookDO record);
}