package plus.bookshelf.Dao.Mapper;

import plus.bookshelf.Dao.DO.CategoryDO;

public interface CategoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_info
     *
     * @mbg.generated
     */
    int insert(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_info
     *
     * @mbg.generated
     */
    int insertSelective(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_info
     *
     * @mbg.generated
     */
    CategoryDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CategoryDO record);

    CategoryDO[] selectChildrenByCategoryId(Integer id);
}