package plus.bookshelf.Dao.Mapper;

import org.springframework.stereotype.Repository;
import plus.bookshelf.Dao.DO.CosPresignedUrlGenerateLogDO;

@Repository // 添加这个注解，Autowired的时候idea就不会报错了
public interface CosPresignedUrlGenerateLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cos_presigned_url_generate_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cos_presigned_url_generate_log
     *
     * @mbg.generated
     */
    int insert(CosPresignedUrlGenerateLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cos_presigned_url_generate_log
     *
     * @mbg.generated
     */
    int insertSelective(CosPresignedUrlGenerateLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cos_presigned_url_generate_log
     *
     * @mbg.generated
     */
    CosPresignedUrlGenerateLogDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cos_presigned_url_generate_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CosPresignedUrlGenerateLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cos_presigned_url_generate_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CosPresignedUrlGenerateLogDO row);
}