package plus.bookshelf.Dao.Mapper;

import org.springframework.stereotype.Repository;
import plus.bookshelf.Dao.DO.FailureFeedbackDO;

@Repository // 添加这个注解，Autowired的时候idea就不会报错了
public interface FailureFeedbackDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failure_feedback
     *
     * @mbg.generated
     */
    int insert(FailureFeedbackDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failure_feedback
     *
     * @mbg.generated
     */
    int insertSelective(FailureFeedbackDO row);
}