package plus.bookshelf.Dao.Mapper;

import plus.bookshelf.Dao.DO.FileOperationDO;

public interface FileOperationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_operation_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_operation_log
     *
     * @mbg.generated
     */
    int insert(FileOperationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_operation_log
     *
     * @mbg.generated
     */
    int insertSelective(FileOperationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_operation_log
     *
     * @mbg.generated
     */
    FileOperationDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_operation_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FileOperationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_operation_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FileOperationDO record);
}