package plus.bookshelf.Dao.Mapper;

import org.springframework.stereotype.Repository;
import plus.bookshelf.Dao.DO.FileObjectDO;

@Repository // 添加这个注解，Autowired的时候idea就不会报错了
public interface FileObjectDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_object_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_object_info
     *
     * @mbg.generated
     */
    int insert(FileObjectDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_object_info
     *
     * @mbg.generated
     */
    int insertSelective(FileObjectDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_object_info
     *
     * @mbg.generated
     */
    FileObjectDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_object_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FileObjectDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_object_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FileObjectDO row);

    /**
     * 查询系统中的所有文件对象
     *
     * @return
     */
    FileObjectDO[] selectAll();

    /**
     * 通过文件路径获取文件
     *
     * @param filePath 文件路径
     * @return
     */
    FileObjectDO selectByFilePath(String filePath);
}