package plus.bookshelf.Dao.Mapper;

import plus.bookshelf.Dao.DO.PublishingHouseDO;

public interface PublishingHouseDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_house_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_house_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int insert(PublishingHouseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_house_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int insertSelective(PublishingHouseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_house_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    PublishingHouseDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_house_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int updateByPrimaryKeySelective(PublishingHouseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_publishing_house_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int updateByPrimaryKey(PublishingHouseDO record);
}