package plus.bookshelf.Dao.Mapper;

import org.springframework.stereotype.Repository;
import plus.bookshelf.Dao.DO.ScheduleTaskDO;

@Repository // 添加这个注解，Autowired的时候idea就不会报错了
public interface ScheduleTaskDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated
     */
    int insert(ScheduleTaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated
     */
    int insertSelective(ScheduleTaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated
     */
    ScheduleTaskDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ScheduleTaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ScheduleTaskDO record);

    /**
     * 从数据库中取出需要处理的任务
     *
     * @return
     */
    ScheduleTaskDO[] selectTodoTask();

    /**
     * 通过 GUID 获取任务
     *
     * @param taskGuid
     * @return
     */
    ScheduleTaskDO selectByGuid(String taskGuid);
}