package plus.bookshelf.Dao.Mapper;

import org.springframework.stereotype.Repository;
import plus.bookshelf.Dao.DO.ThirdPartyUserAuthDO;
import plus.bookshelf.Dao.DO.ThirdPartyUserDO;

@Repository // 添加这个注解，Autowired的时候idea就不会报错了
public interface ThirdPartyUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party_user_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party_user_info
     *
     * @mbg.generated
     */
    int insert(ThirdPartyUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party_user_info
     *
     * @mbg.generated
     */
    int insertSelective(ThirdPartyUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party_user_info
     *
     * @mbg.generated
     */
    ThirdPartyUserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ThirdPartyUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThirdPartyUserDO record);

    /**
     * 通过 uuid + source 查询第三方登录的用户信息（limit 1）
     * @param uuid
     * @param source
     * @return
     */
    ThirdPartyUserDO selectByUuidAndSource(String uuid, String source);
}