package plus.bookshelf.Dao.Mapper;

import plus.bookshelf.Dao.DO.ThirdPartyUserDO;

public interface ThirdPartyUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party_user_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party_user_info
     *
     * @mbg.generated
     */
    int insert(ThirdPartyUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party_user_info
     *
     * @mbg.generated
     */
    int insertSelective(ThirdPartyUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party_user_info
     *
     * @mbg.generated
     */
    ThirdPartyUserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ThirdPartyUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table third_party_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ThirdPartyUserDO record);
}