package plus.bookshelf.Dao.Mapper;

import plus.bookshelf.Dao.DO.ThumbnailDO;

public interface ThumbnailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_thumbnail_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_thumbnail_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int insert(ThumbnailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_thumbnail_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int insertSelective(ThumbnailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_thumbnail_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    ThumbnailDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_thumbnail_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int updateByPrimaryKeySelective(ThumbnailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_thumbnail_info
     *
     * @mbg.generated Sat Mar 12 18:53:08 SGT 2022
     */
    int updateByPrimaryKey(ThumbnailDO record);
}