package plus.bookshelf.Dao.Mapper;

import org.springframework.stereotype.Repository;
import plus.bookshelf.Dao.DO.VisitorFingerprintLogDO;

@Repository // 添加这个注解，Autowired的时候idea就不会报错了
public interface VisitorFingerprintLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_fingerprint_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_fingerprint_log
     *
     * @mbg.generated
     */
    int insert(VisitorFingerprintLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_fingerprint_log
     *
     * @mbg.generated
     */
    int insertSelective(VisitorFingerprintLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_fingerprint_log
     *
     * @mbg.generated
     */
    VisitorFingerprintLogDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_fingerprint_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VisitorFingerprintLogDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_fingerprint_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VisitorFingerprintLogDO row);
}